package com.codenavigator.graph;

public enum NodeType {
    // Tier 1: Generic Java
    CLASS, INTERFACE, RECORD, ENUM,
    CONTROLLER, SERVICE, REPOSITORY, ENTITY,
    CONFIGURATION, MAPPER,
    // Tier 2: Spring Boot
    VIEW, EVENT_PUBLISHER,
    // Tier 3: DDD/CQRS
    COMMAND, COMMAND_HANDLER, QUERY, QUERY_HANDLER,
    AGGREGATE, DOMAIN_EVENT, EVENT_APPLIER,
    PROJECTION_HANDLER, EVENT_LISTENER,
    // Frontend
    FE_SERVICE, FE_COMPONENT, FE_MODEL,
    // Frontend (extended) + scripts
    FE_CLASS, FE_ENUM, FE_PIPE, FE_GUARD, FE_INTERCEPTOR, FE_VALIDATOR, FE_CONSTANT,
    GROOVY_SCRIPT,
    // External
    LIBRARY
}
